version: '3.8'

services:
  # Database Service (Using official image, no need to push)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend Service
  api:
    build: ./backend
    image: manojgk0210/mean-api:latest  # <--- Added Docker Hub destination
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/tutorial_db 
    depends_on:
      - mongodb

  # Frontend Service
  web:
    build: ./frontend
    image: manojgk0210/mean-frontend:latest # <--- Added Docker Hub destination
    ports:
      - "8081:80"
    depends_on:
      - api

volumes:
  mongo-data:
